name: bilibili-daily-task

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 0 * * *'
    # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天14点10分

jobs:
  run-bilibili-tool:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run
      env:
        userId: ${{secrets.USERID}}
        sessData: ${{secrets.SESSDATA}}
        biliJct: ${{secrets.BILIJCT}}
        otherConfigs: ${{secrets.OTHERCONFIGS}}
      run: dotnet run -p ./src/Ray.BiliBiliTool.Console -userId=${224345626} -sessData=${ed5be2eb%2C1664445329%2C21868%2A41} -biliJct=${bbfc05e4c93777a3e225e5d92724d191} -closeConsoleWhenEnd=1 ${otherConfigs}
